// Generated by optimize-stickers.py — do not edit by hand
window.STICKERS = [
  "IMG_9154.webp",
  "IMG_9160.webp",
  "IMG_9208.webp",
  "IMG_9213.webp",
  "IMG_9215.webp",
  "IMG_9219.webp",
  "IMG_9225.webp",
  "IMG_9227.webp",
  "IMG_9231.webp",
  "IMG_9237.webp",
  "IMG_9311.webp",
  "IMG_9559.webp",
  "IMG_9626.webp",
  "IMG_9628.webp",
  "IMG_9630.webp"
];
