# Takes the originals in stickers-originals/, crops the transparent border,
# resizes them and saves them as light WebP files in stickers/.
# Also writes stickers/stickers.js with the list for the web page.
#
# Run every time you add, remove or rename stickers:
#   python3 optimize-stickers.py
import json
from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).parent
SRC = ROOT / "stickers-originals"
OUT = ROOT / "stickers"
MAX_SIDE = 500     # px; enough for the biggest size on screen, even on retina
QUALITY = 80       # WebP quality (0-100)
EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".avif"}

OUT.mkdir(exist_ok=True)
names = []

for src in sorted(SRC.iterdir(), key=lambda p: p.name.lower()):
    if src.suffix.lower() not in EXTS:
        continue
    name = src.stem + ".webp"
    dst = OUT / name
    names.append(name)
    if dst.exists() and dst.stat().st_mtime >= src.stat().st_mtime:
        continue  # already up to date

    im = ImageOps.exif_transpose(Image.open(src)).convert("RGBA")
    if im.getchannel("A").getextrema()[0] > 250:
        print(f"  ⚠ {src.name} has no transparent background — it will show as a rectangle")
    # Crop the empty transparent border around the sticker
    bbox = im.getchannel("A").point(lambda a: 255 if a > 8 else 0).getbbox()
    if bbox:
        im = im.crop(bbox)
    im.thumbnail((MAX_SIDE, MAX_SIDE), Image.LANCZOS)
    im.save(dst, "WEBP", quality=QUALITY, method=6)
    print(f"  {src.name} -> {name} ({dst.stat().st_size // 1024} KB)")

# Remove optimized files whose original was deleted
for old in OUT.glob("*.webp"):
    if old.name not in names:
        old.unlink()
        print(f"  removed {old.name}")

(OUT / "stickers.js").write_text(
    "// Generated by optimize-stickers.py — do not edit by hand\n"
    f"window.STICKERS = {json.dumps(names, indent=2)};\n"
)
print(f"{len(names)} sticker(s) ready in stickers/")
